package au.com.polly.license;

/**
 * Different tasks that can be conducted within the DDR system.
 */
public enum Task
{
LOAD_SMALL_SPREADSHEET,
LOAD_LARGE_SPREADSHEET,
WRITE_SMALL_LAS_FILE,
WRITE_LARGE_LAS_FILE,
REDUCE_SMALL_LAS_FILE,
REDUCE_LARGE_LAS_FILE,
WRITE_REDUCED_LAS_FILE,
GENERATE_OILFLOW_REDUCTION,
GENERATE_FLOW_REDUCTION,
VIEW_REDUCED_BOUNDARIES,
EDIT_REDUCED_BOUNDARIES,
ADD_REDUCED_BOUNDAIES,
GENERATE_BESTFIT_REDUCTION
}
